import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Provider from "@/components/Provider";
import TopNav from "@/components/navbar/TopNav";


export const metadata: Metadata = {
  title: "Next Match",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <Provider>
          <TopNav />
          <main className='container mx-auto p-10'>
              {children}
          </main>
      </Provider>
      </body>
    </html>
  );
}
